name: PHP Teste

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          ini-values: zend.assertions=1, assert.exception=1

      - name: Configurar banco de dados MySQL
        uses: mirromutth/mysql-action@v1
        with:
          mysql database: "projeto_base"
          mysql user: "root"
          mysql password: ""

      - name: Executar testes
        run: php app/tests/runTests.php
